Make network select more stable
oraclesorg/oracles-dapps-validators pull request #112
Opened 2019-08-02 16:07 UTC by maxaleks

- detect when the wallet is unlocked
- store selected network in local storage to prevent network change when:
    - the browser tab is not active
    - we refresh the page having different selected networks in app and extension

2019-08-20 10:16 UTC, igorbarinov commented
@varasev @vbaranov please review when you have time

2019-08-20 19:39 UTC, varasev commented
@maxaleks Please describe here all the scenarios of switching networks (what happens when we switch in the old version of MetaMask; when we switch in the new version of MetaMask; when we switch with a drop-down list of the DApp; when we switch to a non-POA network). This will help to understand what has changed compared to the current version in the `master` branch.

2019-08-20 19:49 UTC, varasev commented
Also, it would be better to rebase it onto the `master` branch.

2019-08-21 10:04 UTC, maxaleks commented
> Also, it would be better to rebase it onto the `master` branch.

@varasev I'm not sure that other changes work good. My task was to fix the network select that is implemented on `prepared-for-network-select` branch

2019-08-22 19:09 UTC, vbaranov requested changes
@maxaleks 

>extension: switching the network to the one of four valid networks also changes the network in the app

I tried to switch from 
1. Sokol -> Poa Core
2. Sokol -> xDai

from Nifty wallet extension and application didn't change the state. Btw, changes to Kovan or Sokol were successful.

2019-08-24 10:44 UTC, varasev requested changes
Switching doesn't work: being worked with xDai I tried to add Sokol network to MetaMask and refresh the page - the network in the app didn't switch to Sokol. After that, any attempts to switch network in the MetaMask don't lead to switching to the same network in the app.

2019-08-24 10:47 UTC, varasev commented
@maxaleks I used MetaMask 7.0.1 ☝️ Please test different cases of switching after code changing.

2019-08-24 19:58 UTC, varasev commented
Steps to reproduce:

1. Initially, I have the following set of networks in my MetaMask, and my selected network is Kovan:

<img src="https://user-images.githubusercontent.com/33550681/63642033-08321b00-c6c1-11e9-8c89-2f47c0e98b59.png" width="200" />

2. Run `npm start` and `http://localhost:3000/poa-dapps-validators` is opened. The selected network in the DApp is `Kovan` as expected.

3. Add a new RPC address to MetaMask: `https://sokol.poa.network`. The network in the DApp is switched to `Sokol` as expected.

4. Then I switch back to `Kovan` in MetaMask. DApp switched to `Kovan` as well.

5. Then I switch to `Sokol` in MetaMask. DApp page is refreshed but displays `Kovan` network.

6. I refresh the browser page but still see `Kovan` selected in DApp and `Sokol` selected in MetaMask.

2019-09-11 19:11 UTC, maxaleks commented
**Update:** Now the network of the app can be switched only using the in-app switcher

2019-10-24 13:44 UTC, varasev approved these changes

2019-10-24 13:48 UTC, varasev commented
@vbaranov Would you check this PR again? Or can we merge this immediately? Today I made here a few fixes and refactorings, tested this with `poa-test-setup` (using https://github.com/poanetwork/poa-dapps-validators/pull/112), and manually tested different scenarios. Everything looks fine. If you test this, please note that the list of changes was updated: https://github.com/poanetwork/poa-dapps-validators/pull/112#issue-303847125 (changes were simplified a bit).

2019-10-24 13:48 UTC, vbaranov commented
@varasev I am on it

2019-10-24 13:55 UTC, vbaranov commented
@varasev 

>The network of the app can be switched only using the in-app switcher

what is the reason for that?

2019-10-24 13:59 UTC, vbaranov commented on src/index.js
> +    console.log('newState:')
@varasev do we need it in production?

2019-10-24 14:00 UTC, vbaranov commented on src/index.js
> +    console.log(newState)
@varasev do we need it in production?

2019-10-24 14:01 UTC, varasev commented on src/index.js
> +    console.log(newState)
@maxaleks please remove those lines

2019-10-24 14:04 UTC, varasev commented
> > The network of the app can be switched only using the in-app switcher
> 
> what is the reason for that?

@vbaranov As far as I understand, there were some troubles with switching networks in different MetaMask (and Nifty Wallet) versions, so we decided to remove the switching and add a check for `netId` matching when a transaction is about to be executed. @maxaleks can provide details of the problem

2019-10-24 14:11 UTC, maxaleks commented on src/index.js
> +    console.log(newState)
Done. But they were not added by me

2019-10-24 14:23 UTC, maxaleks commented
> @vbaranov As far as I understand, there were some troubles with switching networks in different MetaMask (and Nifty Wallet) versions, so we decided to remove the switching and add a check for netId matching when a transaction is about to be executed. @maxaleks can provide details of the problem

In old versions of Metamask and NW the network switching reloads the page and in most cases the page reloads before we receive a network change event

2019-10-24 14:40 UTC, vbaranov commented
@maxaleks 

>In old versions of Metamask and NW the network switching reloads the page and in most cases the page is reloaded before we receive a network change event

I tried today the latest version of NW and the currently deployed version of validators dapp and it perfectly switches between chains if I switch them in NW.

2019-10-24 14:51 UTC, maxaleks commented
@vbaranov 
> I tried today the latest version of NW and the currently deployed version of validators dapp and it perfectly switches between chains if I switch them in NW.

The task also was to show the in-app network switch in both cases: with and without NW/Metamask. So there were conflicts when we allowed switching the network in the app and in NW/Metamask

2019-10-24 14:57 UTC, varasev commented
What if we turn on the switching in MM/NW again like it is currently implemented in the current https://validators.poa.network/ ? I.e. when we switch the network in MM/NW, the network is automatically switched in App.

If we switch network in App, it won't be switched in MM/NW, but the alert will be shown if we try to make a transaction in a different network (as already implemented in this PR).

@maxaleks Would you expect any troubles in this case?

2019-10-24 15:39 UTC, maxaleks commented
> What if we turn on the switching in MM/NW again like it is currently implemented in the current https://validators.poa.network/ ? I.e. when we switch the network in MM/NW, the network is automatically switched in App.
If we switch network in App, it won't be switched in MM/NW, but the alert will be shown if we try to make a transaction in a different network (as already implemented in this PR).
@maxaleks Would you expect any troubles in this case?

Should we store the selected network?
1. If I have `Kovan` selected in my Metamask and I switch the network to `Sokol` in the app, and then reload the page, then which network should be selected after reloading?
2. I have `Kovan` selected in both app and Metamask. Then I go to another dApp (our tab is not active) and switch the network to `Sokol`. The page of our app will be reloaded. Which network should be selected in this case?

Earlier we discussed that we should store the selected network, so these are those conflicts that I mentioned in the previous comment

2019-10-24 17:36 UTC, varasev commented
The second case (when a user opens another DApp in another browser tab) is unlikely, so if the network is switched in MetaMask, we should switch it in DApp as well.

And, in general, it's better to automatically switch the network in DApp when it's switched in MetaMask (if that network is Core/Sokol/Kovan/xDai, i.e. supported by DApp).

But in the case when the user reloads DApp's page, the user would expect to see the same network they had seen before they reloaded the page (regardless which network is chosen in MetaMask).

I think we could handle such a case with page reloading, couldn't we?

I.e. switch the network in DApp to MetaMask's if this is not a page reloading, but keep the network the same if this is a page reloading.

Is that possible to distinguish the cause of current network's switching (reloading by user or by MetaMask)?

If that's not possible, then I think the reloading is unlikely operation, especially when a user just watch the content of the DApp and is not going to make any transactions. So, in general we would just always switch the network in App automatically when it is occured in MetaMask, and keep the current logic implemented in this PR (comparing `netId` when needed).

2019-10-24 17:49 UTC, varasev commented
> In old versions of Metamask and NW the network switching reloads the page and in most cases the page is reloaded before we receive a network change event

That problem is only actual for old versions of MM/NW?

2019-10-24 17:51 UTC, maxaleks commented
> That problem is only actual for old versions of MM/NW, right?

For old version of MM and any version of NW

2019-10-25 06:04 UTC, varasev commented
On the other hand, users won't use MetaMask's network switcher because now it's easier and faster to do that through the upper right drop-down list, so we could leave the current behavior since it seems to be better from UX/UI perspective (because it keeps the network when a user switches to another browser tab or reloads the page).

Another kind of user - validator - to make a transaction will switch the network in MetaMask only once, so it's infrequent operation.

I propose to leave the current implementation.

2019-10-25 06:28 UTC, varasev commented
Another possible solution: automatically switch the network in App when it's switched in MM only when the current user is a validator (i.e. [`miningKey`](https://github.com/poanetwork/poa-dapps-validators/blob/1825671b0eaa13262f0bd45394347a57c0e0f97a/src/index.js#L131) is not `0x000...000`). @vbaranov what do you think?

2019-10-25 06:43 UTC, varasev commented
> Another possible solution: automatically switch the network in App when it's switched in MM only when the current user is a validator (i.e. [`miningKey`](https://github.com/poanetwork/poa-dapps-validators/blob/1825671b0eaa13262f0bd45394347a57c0e0f97a/src/index.js#L131) is not `0x000...000`).

Sorry, bad idea, because `miningKey` is always zero until we are in right network.

2019-10-25 09:26 UTC, maxaleks commented
I agree with @varasev. Most users of our app don't need Metamask at all, because they don't send any transactions. So for these users it will be easier if they could switch network only in app

2019-10-25 09:40 UTC, vbaranov commented
@maxaleks @varasev the last point makes to change my mind regarding the updates ✔️

2019-10-25 09:40 UTC, vbaranov approved these changes

2019-10-25 09:55 UTC, merged

2019-10-28 17:33 UTC, 6proof commented
As of time  of this  post, the switch at https://validators.poa.network/poa-dapps-validators seems to only work manually; no longer switches automatically based  on RPC server selection.  It would  be nice  to have the 'correct' page / network appear based on RPC server selection when first visiting page, with the ability to choose other  networks  manually via drop down selection.

2019-10-29 08:04 UTC, varasev commented
@6proof OK, opened an issue for that: https://github.com/poanetwork/poa-dapps-validators/issues/115